// Knowledge base for identifying email services from DNS records
export const KB = {
    mx: [
        { pattern: 'protection.outlook.com', name: 'Microsoft 365', type: 'provider' },
        { pattern: 'mail.protection.outlook.com', name: 'Microsoft 365', type: 'provider' },
        { pattern: 'google.com', name: 'Google Workspace', type: 'provider' },
        { pattern: 'googlemail.com', name: 'Google Workspace', type: 'provider' },
        { pattern: 'pphosted.com', name: 'Proofpoint', type: 'seg' },
        { pattern: 'ppe-hosted.com', name: 'Proofpoint', type: 'seg' },
        { pattern: 'mimecast.com', name: 'Mimecast', type: 'seg' },
        { pattern: 'barracudanetworks.com', name: 'Barracuda', type: 'seg' },
        { pattern: 'barracuda.com', name: 'Barracuda', type: 'seg' },
        { pattern: 'fortimailcloud.com', name: 'FortiMail (Fortinet)', type: 'seg' },
        { pattern: 'fortimail.com', name: 'FortiMail (Fortinet)', type: 'seg' },
        { pattern: 'iphmx.com', name: 'Cisco Email Security (IronPort)', type: 'seg' },
        { pattern: 'ess.cisco.com', name: 'Cisco Email Security', type: 'seg' },
        { pattern: 'trendmicro.com', name: 'Trend Micro Email Security', type: 'seg' },
        { pattern: 'in.trendmicro.com', name: 'Trend Micro Email Security', type: 'seg' },
        { pattern: 'sophos.com', name: 'Sophos Email', type: 'seg' },
        { pattern: 'fireeye.com', name: 'FireEye Email Security', type: 'seg' },
        { pattern: 'messagelabs.com', name: 'Symantec Email Security', type: 'seg' },
        { pattern: 'symanteccloud.com', name: 'Symantec Email Security', type: 'seg' },
        { pattern: 'securence.com', name: 'Securence', type: 'seg' },
        { pattern: 'spamexperts.com', name: 'SpamExperts', type: 'seg' },
        { pattern: 'hornetsecurity.com', name: 'Hornetsecurity', type: 'seg' },
        { pattern: 'zoho.com', name: 'Zoho Mail', type: 'provider' },
        { pattern: 'yahoodns.net', name: 'Yahoo Mail', type: 'provider' },
        { pattern: 'amazonaws.com', name: 'Amazon SES/WorkMail', type: 'provider' },
        { pattern: 'secureserver.net', name: 'GoDaddy Email', type: 'provider' },
        { pattern: 'emailsrvr.com', name: 'Rackspace Email', type: 'provider' },
        { pattern: 'ovh.net', name: 'OVH Mail', type: 'provider' },
        { pattern: 'ionos.com', name: 'IONOS Mail', type: 'provider' },
    ],
    spf: [
        { pattern: 'spf.protection.outlook.com', name: 'Microsoft 365', category: 'email', cat_label: 'Proveedor Email' },
        { pattern: '_spf.google.com', name: 'Google Workspace', category: 'email', cat_label: 'Proveedor Email' },
        { pattern: 'amazonses.com', name: 'Amazon SES', category: 'transactional', cat_label: 'Transaccional' },
        { pattern: 'sendgrid.net', name: 'SendGrid (Twilio)', category: 'transactional', cat_label: 'Transaccional' },
        { pattern: 'mailgun.org', name: 'Mailgun', category: 'transactional', cat_label: 'Transaccional' },
        { pattern: 'mandrillapp.com', name: 'Mandrill (Mailchimp)', category: 'transactional', cat_label: 'Transaccional' },
        { pattern: 'postmarkapp.com', name: 'Postmark', category: 'transactional', cat_label: 'Transaccional' },
        { pattern: 'sparkpostmail.com', name: 'SparkPost', category: 'transactional', cat_label: 'Transaccional' },
        { pattern: 'mailjet.com', name: 'Mailjet', category: 'transactional', cat_label: 'Transaccional' },
        { pattern: 'sendinblue.com', name: 'Brevo (Sendinblue)', category: 'transactional', cat_label: 'Transaccional' },
        { pattern: 'brevosend.com', name: 'Brevo', category: 'transactional', cat_label: 'Transaccional' },
        { pattern: 'exclaimer.net', name: 'Exclaimer', category: 'signatures', cat_label: 'Firmas Email' },
        { pattern: 'exclaimer.com', name: 'Exclaimer', category: 'signatures', cat_label: 'Firmas Email' },
        { pattern: 'codetwo.com', name: 'CodeTwo', category: 'signatures', cat_label: 'Firmas Email' },
        { pattern: 'salesforce.com', name: 'Salesforce', category: 'crm', cat_label: 'CRM' },
        { pattern: 'hubspot.com', name: 'HubSpot', category: 'crm', cat_label: 'CRM/Marketing' },
        { pattern: 'mktomail.com', name: 'Marketo (Adobe)', category: 'marketing', cat_label: 'Marketing' },
        { pattern: 'mktoweb.com', name: 'Marketo (Adobe)', category: 'marketing', cat_label: 'Marketing' },
        { pattern: 'servers.mcsv.net', name: 'Mailchimp', category: 'marketing', cat_label: 'Marketing' },
        { pattern: 'mailchimp.com', name: 'Mailchimp', category: 'marketing', cat_label: 'Marketing' },
        { pattern: 'constantcontact.com', name: 'Constant Contact', category: 'marketing', cat_label: 'Marketing' },
        { pattern: 'campaignmonitor.com', name: 'Campaign Monitor', category: 'marketing', cat_label: 'Marketing' },
        { pattern: 'activecampaign.com', name: 'ActiveCampaign', category: 'marketing', cat_label: 'Marketing' },
        { pattern: 'klaviyo.com', name: 'Klaviyo', category: 'marketing', cat_label: 'Marketing' },
        { pattern: 'mlsend.com', name: 'MailerLite', category: 'marketing', cat_label: 'Marketing' },
        { pattern: 'mailerlite.com', name: 'MailerLite', category: 'marketing', cat_label: 'Marketing' },
        { pattern: 'zendesk.com', name: 'Zendesk', category: 'support', cat_label: 'Soporte' },
        { pattern: 'freshdesk.com', name: 'Freshdesk', category: 'support', cat_label: 'Soporte' },
        { pattern: 'intercom.io', name: 'Intercom', category: 'support', cat_label: 'Soporte' },
        { pattern: 'helpscout.net', name: 'Help Scout', category: 'support', cat_label: 'Soporte' },
        { pattern: 'zoho.com', name: 'Zoho', category: 'email', cat_label: 'Proveedor Email' },
        { pattern: 'zoho.eu', name: 'Zoho', category: 'email', cat_label: 'Proveedor Email' },
        { pattern: 'fortimailcloud.com', name: 'FortiMail (Fortinet)', category: 'seg', cat_label: 'SEG' },
        { pattern: 'fortimail.com', name: 'FortiMail (Fortinet)', category: 'seg', cat_label: 'SEG' },
        { pattern: 'pphosted.com', name: 'Proofpoint', category: 'seg', cat_label: 'SEG' },
        { pattern: 'proofpoint.com', name: 'Proofpoint', category: 'seg', cat_label: 'SEG' },
        { pattern: 'mimecast.com', name: 'Mimecast', category: 'seg', cat_label: 'SEG' },
        { pattern: 'barracuda', name: 'Barracuda', category: 'seg', cat_label: 'SEG' },
        { pattern: 'sophos.com', name: 'Sophos', category: 'seg', cat_label: 'SEG' },
        { pattern: 'trendmicro.com', name: 'Trend Micro', category: 'seg', cat_label: 'SEG' },
        { pattern: 'cisco.com', name: 'Cisco Email Security', category: 'seg', cat_label: 'SEG' },
        { pattern: 'mcafee.com', name: 'McAfee', category: 'seg', cat_label: 'SEG' },
        { pattern: 'avanan.net', name: 'Avanan (Check Point)', category: 'ices', cat_label: 'ICES' },
        { pattern: 'abnormalsecurity.com', name: 'Abnormal Security', category: 'ices', cat_label: 'ICES' },
        { pattern: 'ironscales.com', name: 'Ironscales', category: 'ices', cat_label: 'ICES' },
        { pattern: 'darktrace.com', name: 'Darktrace', category: 'ices', cat_label: 'ICES' },
        { pattern: 'tessian.com', name: 'Tessian', category: 'ices', cat_label: 'ICES' },
        { pattern: 'knowbe4.com', name: 'KnowBe4', category: 'other', cat_label: 'Concienciación' },
        { pattern: 'docusign.com', name: 'DocuSign', category: 'other', cat_label: 'Firmas Digitales' },
        { pattern: 'netsuite.com', name: 'NetSuite (Oracle)', category: 'crm', cat_label: 'ERP/CRM' },
        { pattern: 'workday.com', name: 'Workday', category: 'other', cat_label: 'RRHH' },
        { pattern: 'servicenow.com', name: 'ServiceNow', category: 'other', cat_label: 'ITSM' },
        { pattern: 'fideltour.com', name: 'Fideltour', category: 'other', cat_label: 'Turismo/CRM' },
        { pattern: 'managed-otrs.com', name: 'OTRS', category: 'support', cat_label: 'Soporte/ITSM' },
    ],
    dmarc_reporters: [
        { pattern: 'agari.com', name: 'Agari' },
        { pattern: 'dmarcian.com', name: 'Dmarcian' },
        { pattern: 'valimail.com', name: 'Valimail' },
        { pattern: 'easydmarc.com', name: 'EasyDMARC' },
        { pattern: 'postmarkapp.com', name: 'Postmark' },
        { pattern: 'ondmarc.com', name: 'Red Sift OnDMARC' },
        { pattern: 'dmarc.microsoft.com', name: 'Microsoft' },
        { pattern: 'google.com', name: 'Google' },
        { pattern: 'proofpoint.com', name: 'Proofpoint' },
        { pattern: 'mimecast.com', name: 'Mimecast' },
        { pattern: 'powerdmarc.com', name: 'PowerDMARC' },
        { pattern: 'uriports.com', name: 'URIports' },
    ],
    categoryColors: {
        email: '#6366f1', seg: '#a855f7', ices: '#8b5cf6',
        marketing: '#f59e0b', transactional: '#06b6d4', crm: '#10b981',
        signatures: '#f43f5e', support: '#fb923c', other: '#64748b',
        unknown: '#9ca3af'
    }
};

// Cargar entradas personalizadas guardadas por el usuario
try {
    const customKB = localStorage.getItem('custom_kb_spf');
    if (customKB) {
        const entries = JSON.parse(customKB);
        if (Array.isArray(entries)) {
            KB.spf.push(...entries);
        }
    }
} catch (e) {
    console.error('Error loading custom KB from localStorage', e);
}
